name: Main branch

on:
  push:
    branches:
      - "main"
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir-version: ['1.17.3']
        otp-version: ['27.1']

    steps:
    - name: Run tests
      uses: bonfire-networks/bonfire-extension-ci-action@latest
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
